[build-system]
requires = ['setuptools>=40.8.0', 'wheel']
build-backend = 'setuptools.build_meta:__legacy__'

[tool.black]
skip-string-normalization = true
extend-exclude = '''
/(
  django/forms/models.py
  | docs
  | scripts
  | tests/test_runner_apps/tagged/tests_syntax_error.py
)/
'''
