[build-system]
requires = ['setuptools>=40.8.0', 'wheel']
build-backend = 'setuptools.build_meta:__legacy__'

[tool.black]
skip-string-normalization = true
extend-exclude = '''
/(
  (
    docs
    | scripts
  )/
  | django/forms/models.py
  | tests/gis_tests/test_spatialrefsys.py
  | tests/test_runner_apps/tagged/tests_syntax_error.py
)
'''
